[libdefaults]
	default_realm = AETHER.TEST
	dns_lookup_realm = false
	dns_lookup_kdc = false
	rdns = false
	udp_preference_limit = 1

[realms]
	AETHER.TEST = {
		kdc = 172.18.0.2
		admin_server = 172.18.0.2
	}

[domain_realm]
	.aether.test = AETHER.TEST
	aether.test = AETHER.TEST
